---
- name: SARS-CoV-2 pipeline - ensure "{{ ansible_user_id }}" is in group docker
  user:
   name: "{{ ansible_user_id }}"
   groups: docker
   append: yes
  become: yes

- name: reset ssh connection
  meta: reset_connection

- name: SARS-CoV-2 pipeline - build auspice image
  community.general.docker_image:
    name: auspice
    build:
      path: "{{ docker_build.path }}"
      pull: no
      dockerfile: Dockerfile.auspice
    source: build
    state: present
    tag: 1.0.0
  become: yes