---
- name: SARS-CoV-2 pipeline - init submodules
  command: git submodule init
  args:
    chdir: "{{ git_submod.path }}"

- name: SARS-CoV-2 pipeline - update submodules
  command: git submodule update --remote --merge
  args:
    chdir: "{{ git_submod.path }}"

- debug:
    msg: User {{ ansible_user_id }}

- debug:
    msg: Path {{ playbook_dir }}

- name: SARS-CoV-2 pipeline - ensure user is in group docker
  user:
   name: "{{ ansible_user_id }}"
   groups: docker
   append: yes
  become: yes

- name: reset ssh connection
  meta: reset_connection

- name: SARS-CoV-2 pipeline - build pangolin image
  community.general.docker_image:
    name: pangolin
    build:
      path: "{{ docker_build.path }}"
      pull: no
      dockerfile: Dockerfile.pangolin
    source: build
    state: present
    tag: 1.0.0
  become: yes