repos:

-   repo: https://github.com/ambv/black
    rev: 20.8b0
    hooks:
    - id: black
      args: [--target-version=py38, --line-length=120]
      language_version: python3.8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
    -   id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
    - id: pylint
      exclude: 'manage.py|tests|setup.py'
      args: [
        --max-line-length=120,
        --disable=design,
        --disable=missing-docstring,
        --disable=bad-continuation,
        --disable=max-module-lines,
        --disable=useless-super-delegation,
        --disable=import-error,
        --disable=logging-fstring-interpolation,
        --disable=invalid-name,
        --disable=duplicate-code,
        --disable=broad-except,
        --disable=logging-format-interpolation,
        --disable=too-many-lines
      ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args: [--max-line-length=120, '--ignore=E203,W503']
      exclude: 'manage.py'
