name: htstools
channels:
  - bioconda
  - conda-forge # required for awscli
dependencies:
  - awscli=1.25.92
  - procps-ng=4.0.3   # required for ps
  - htslib=1.16
  - samtools=1.16.1
  - bcftools=1.16
