---
- name: SARS-CoV-2 pipeline - restart docker
  become_user: root
  systemd:
    state: restarted
    name: docker

- name: SARS-CoV-2 pipeline - pull nextstrain docker image
  docker_image:
    name: nextstrain/base

- name: SARS-CoV-2 pipeline - install nextstrain-cli with pip3
  pip:
    name: nextstrain-cli
    executable: pip3
    extra_args: --user

- name: SARS-CoV-2 pipeline - add nextstrain to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:~/.local/bin/'

- name: SARS-CoV-2 pipeline - create nextstrain config directory
  file: 
    path: ~/.nextstrain
    state: directory

- name: SARS-CoV-2 pipeline - set docker as default runner for nextstrain
  template:
    src: nextstrain_config.j2
    dest: ~/.nextstrain/config

- name: SARS-CoV-2 pipeline - clone the nextstrain ncov git repo
  git:
    repo: 'https://github.com/nextstrain/ncov'
    dest: ~/ncov
