version: 2.1

parameters:
  docker_version:
    type: string
    default: "19.03.13"

executors:
  python:
    docker:
      - image: cimg/python:3.10

commands:
  build_and_push_docker_image:
    parameters:
      dockerfile:
        type: string
      ecrpath:
        type: string
      ecrepouri:
        type: string
      awsregion:
        type: string
      pathogen:
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            pip install --progress-bar off awscli
            eval $(aws ecr get-login --no-include-email --region <<parameters.awsregion>>)
            NORMALISED_SLASHES=${CIRCLE_BRANCH//\//_}
            DOCKER_TAG_BRANCH=${NORMALISED_SLASHES//-/_}
            DOCKER_TAG="${DOCKER_TAG_BRANCH}_${CIRCLE_BUILD_NUM}"
            REGISTRY_URI="<<parameters.ecrepouri>><<parameters.ecrpath>>"
            FULL_TAG="${REGISTRY_URI}:${DOCKER_TAG}"
            LATEST_IMAGE_TAG="${REGISTRY_URI}:${DOCKER_TAG_BRANCH}_latest"
            CIRCLE_TAG="${REGISTRY_URI}:circleci_${CIRCLE_BUILD_NUM}"
            if [ "<< parameters.pathogen >>" == ""];
            then
                docker build -t ${FULL_TAG} -t ${CIRCLE_TAG} -t ${LATEST_IMAGE_TAG} -f docker/<< parameters.dockerfile >> .
            else
                docker build --build-arg pathogen=<< parameters.pathogen >> -t ${FULL_TAG} -t ${CIRCLE_TAG} -t ${LATEST_IMAGE_TAG} -f docker/<< parameters.dockerfile >> .
            fi
            docker push ${FULL_TAG}
            docker push ${CIRCLE_TAG}
            docker push ${LATEST_IMAGE_TAG}
            # Log out the environment vars
            echo "CircleCI url to access"
            echo "${FULL_TAG}"

jobs:
  pre_commit_hooks:
    executor: python
    steps:
      - checkout
      - run:
          name: Run pre-commit checks
          command: |
            pip install pre-commit==2.17.0
            pre-commit run --all-files

  run-unit-tests:
    executor: python
    steps:
      - checkout
      - run:
          name: Install dependencies and run tests
          command: |
            poetry install
            poetry run pytest tests/
  build-sars-cov-2-pipeline:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.psga-pipeline"
          ecrpath: ${SARS_COV_2_PIPELINE_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
  build-read-it-and-keep:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.read-it-and-keep"
          ecrpath: ${READ_IT_AND_KEEP_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
  build-fastqc:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.fastqc"
          ecrpath: ${FASTQC_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
  build-primer-autodetection:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.primer-autodetection"
          ecrpath: ${PRIMER_AUTODETECTION_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
  build-ncov2019-artic-nf-illumina:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.ncov2019-artic-nf-illumina"
          ecrpath: ${NCOV2019_ARTIC_NF_ILLUMINA_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
  build-ncov2019-artic-nf-nanopore:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.ncov2019-artic-nf-nanopore"
          ecrpath: ${NCOV2019_ARTIC_NF_NANOPORE_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
  build-pangolin:
    executor: python
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.pangolin"
          ecrpath: ${PANGOLIN_ECREPOPATH_PSGA}
          ecrepouri: ${ECREPOURI_PSGA}
          awsregion: "eu-west-2"
          pathogen: "sars_cov_2"
# sars-cov-2-pipeline image is built after the others so that Jenkins starts when all images are generated
workflows:
  version: 2
  test_and_build_all:
    jobs:
    - pre_commit_hooks
    - run-unit-tests:
        requires:
          - pre_commit_hooks
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-read-it-and-keep:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-fastqc:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-primer-autodetection:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-ncov2019-artic-nf-illumina:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-ncov2019-artic-nf-nanopore:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-pangolin:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS_PSGA
    - build-sars-cov-2-pipeline:
        requires:
          - read-it-and-keep
          - fastqc
          - primer-autodetection
          - build-ncov2019-artic-nf-illumina
          - build-ncov2019-artic-nf-nanopore
          - build-pangolin
        context: AWS_ECR_CREDENTIALS_PSGA
