version: 2.1

parameters:
  docker_version:
    type: string
    default: "19.03.13"

executors:
  python:
    docker:
      - image: cimg/python:3.9

commands:
  build_and_push_docker_image:
    parameters:
      dockerfile:
        type: string
      ecrpath:
        type: string
      gitsubmodules:
        type: boolean
        default: false
      pathogen:
        type: string
        default: ""
    steps:
      - setup_remote_docker:
          version: << pipeline.parameters.docker_version >>
          docker_layer_caching: true
      - checkout
      - when:
          condition: << parameters.gitsubmodules >>
          steps:
            - run:
                name: Install git submodules
                command: |
                  git submodule init
                  git submodule update
      - run:
          name: Build docker image
          command: |
            pip install --progress-bar off awscli
            eval $(aws ecr get-login --no-include-email --region eu-west-1)
            NORMALISED_SLASHES=${CIRCLE_BRANCH//\//_}
            DOCKER_TAG_BRANCH=${NORMALISED_SLASHES//-/_}
            DOCKER_TAG="${DOCKER_TAG_BRANCH}_${CIRCLE_BUILD_NUM}"
            REGISTRY_URI="${ECREPOURI}<<parameters.ecrpath>>"
            FULL_TAG="${REGISTRY_URI}:${DOCKER_TAG}"
            LATEST_IMAGE_TAG="${REGISTRY_URI}:${DOCKER_TAG_BRANCH}_latest"
            CIRCLE_TAG="${REGISTRY_URI}:circleci_${CIRCLE_BUILD_NUM}"
            if [ "<< parameters.pathogen >>" == ""];
            then
                docker build -t ${FULL_TAG} -t ${CIRCLE_TAG} -t ${LATEST_IMAGE_TAG} -f docker/<< parameters.dockerfile >> .
            else
                docker build --build-arg pathogen=<< parameters.pathogen >> -t ${FULL_TAG} -t ${CIRCLE_TAG} -t ${LATEST_IMAGE_TAG} -f docker/<< parameters.dockerfile >> .
            fi
            docker push ${FULL_TAG}
            docker push ${CIRCLE_TAG}
            docker push ${LATEST_IMAGE_TAG}
            # Log out the environment vars
            echo "CircleCI url to access"
            echo "${FULL_TAG}"

jobs:
  pre_commit_hooks:
    executor: python
    steps:
      - checkout
      - run:
          name: Run pre-commit checks
          command: |
            pip install pre-commit==2.17.0
            pre-commit run --all-files

  run-unit-tests:
    executor: python
    steps:
      - checkout
      - run:
          name: Install dependencies and run tests
          command: |
            poetry install
            poetry run pytest tests/
  build-sars-cov-2-pipeline:
    executor: python
    steps:
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.psga-pipeline"
          ecrpath: ${PSGA_PIPELINE_ECREPOPATH}
          gitsubmodules: false
          pathogen: "sars_cov_2"
  build-ncov2019-artic-nf-illumina:
    executor: python
    steps:
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.ncov2019-artic-nf-illumina"
          ecrpath: ${NCOV2019_ARTIC_NF_ILLUMINA_ECREPOPATH}
          gitsubmodules: true
  build-ncov2019-artic-nf-nanopore:
    executor: python
    steps:
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.ncov2019-artic-nf-nanopore"
          ecrpath: ${NCOV2019_ARTIC_NF_NANOPORE_ECREPOPATH}
          gitsubmodules: true
  build-pangolin:
    executor: python
    steps:
      - build_and_push_docker_image:
          dockerfile: "Dockerfile.pangolin"
          ecrpath: ${PANGOLIN_ECREPOPATH}
          gitsubmodules: true

workflows:
  version: 2
  test_and_build_all:
    jobs:
    - pre_commit_hooks
    - run-unit-tests:
        requires:
          - pre_commit_hooks
        context: AWS_ECR_CREDENTIALS
    - build-sars-cov-2-pipeline:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS
    - build-ncov2019-artic-nf-illumina:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS
    - build-ncov2019-artic-nf-nanopore:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS
    - build-pangolin:
        requires:
          - run-unit-tests
        context: AWS_ECR_CREDENTIALS
