---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-pipeline
spec:
  selector:
    matchLabels:
      app: covid-pipeline
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: covid-pipeline
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: farmNode
                operator: In
                values:
                - "true"
      containers:
      - image: 144563655722.dkr.ecr.eu-west-1.amazonaws.com/congenica/dev/nextflow-wrapper:1.0.0
        imagePullPolicy: Always
        name: covid-pipeline
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: clus_COVID_DB_HOST
              name: db-config
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: clus_COVID_DB_NAME
              name: db-config
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: clus_COVID_DB_PASSWORD
              name: db-config
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: clus_COVID_DB_PORT
              name: db-config
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: clus_COVID_DB_USER
              name: db-config
        - name: COVID_PIPELINE_ROOT_PATH
          value: /app
        - name: COVID_PIPELINE_INPUT_PATH
          value: /data/input
        - name: COVID_PIPELINE_OUTPUT_PATH
          value: /data/output
        - name: NXF_WORK
          value: /data/work
        - name: NXF_EXECUTOR
          value: k8s
        - name: NXF_ANSI_LOG
          value: 'false'
        volumeMounts:
        - name: covid-pipeline-persistent-storage
          mountPath: /data
      volumes:
      - name: covid-pipeline-persistent-storage
        persistentVolumeClaim:
          claimName: covid-pipeline-pvc
