apiVersion: v1
kind: Pod
metadata:
  labels:
    submitterName: piero
  name: covid-db
spec:
  containers:
  - command:
    - /bin/bash
    args:
    - -c
    - "while true; do sleep 30; done;"
    env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          key: clus_COVID_DB_HOST
          name: db-config
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          key: clus_COVID_DB_NAME
          name: db-config
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: clus_COVID_DB_PASSWORD
          name: db-config
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          key: clus_COVID_DB_PORT
          name: db-config
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          key: clus_COVID_DB_USER
          name: db-config
    image: 144563655722.dkr.ecr.eu-west-1.amazonaws.com/congenica/dev/covid-pipeline:1.0.0
    imagePullPolicy: Always
    name: covid-db
    resources:
      limits:
        cpu: "1"
        memory: 5Gi
      requests:
        cpu: "1"
        memory: 5Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    workingDir: /
  dnsPolicy: ClusterFirst
  nodeSelector:
    farmNode: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
