---
- name: SARS-CoV-2 pipeline - set DB_HOST environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_HOST="
    line: "export DB_HOST={{ db_host}}"

- name: SARS-CoV-2 pipeline - set DB_NAME environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_NAME="
    line: "export DB_NAME={{ db_name}}"

- name: SARS-CoV-2 pipeline - set DB_USER environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_USER="
    line: "export DB_USER={{ db_user}}"

- fail:
    msg: "Must supply DB_PASSWORD"
  when: db_password is not defined

- name: SARS-CoV-2 pipeline - set DB_PASSWORD environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_PASSWORD="
    line: "export DB_PASSWORD={{ db_password}}"

- name: SARS-CoV-2 pipeline - set DB_PORT environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_PORT="
    line: "export DB_PORT={{ db_port }}"

- name: SARS-CoV-2 pipeline - set COVID_PIPELINE_ROOTDIR environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export COVID_PIPELINE_ROOTDIR="
    line: "export COVID_PIPELINE_ROOTDIR={{ covid_pipeline_rootdir }}"

- name: SARS-CoV-2 pipeline - set COVID_PIPELINE_FASTQ_PATH environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export COVID_PIPELINE_FASTQ_PATH="
    line: "export COVID_PIPELINE_FASTQ_PATH={{ covid_pipeline_fastq_path }}"

- name: SARS-CoV-2 pipeline - set COVID_PIPELINE_WORKDIR environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export COVID_PIPELINE_WORKDIR="
    line: "export COVID_PIPELINE_WORKDIR={{ covid_pipeline_workdir }}"

- name: SARS-CoV-2 pipeline - set COVID_PIPELINE_REPORTS_PATH environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export COVID_PIPELINE_REPORTS_PATH="
    line: "export COVID_PIPELINE_REPORTS_PATH={{ covid_pipeline_reports_path }}"

- name: SARS-CoV-2 pipeline - set environment extra variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^{{ item.key }}="
    line: "export {{ item.key }}={{ item.value}}"
  with_items: "{{ environment_vars }}"
