---
- name: PSGA pipeline - set DB_HOST environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_HOST="
    line: "export DB_HOST={{ db_host}}"
  register: db_host_register

- name: PSGA pipeline - set DB_NAME environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_NAME="
    line: "export DB_NAME={{ db_name}}"
  register: db_name_register

- name: PSGA pipeline - set DB_USER environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_USER="
    line: "export DB_USER={{ db_user}}"
  register: db_user_register

- fail:
    msg: "Must supply DB_PASSWORD"
  when: db_password is not defined

- name: PSGA pipeline - set DB_PASSWORD environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_PASSWORD="
    line: "export DB_PASSWORD={{ db_password}}"
  register: db_password_register


- name: PSGA pipeline - set DB_PORT environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export DB_PORT="
    line: "export DB_PORT={{ db_port }}"
  register: db_port_register

- name: PSGA pipeline - set PSGA_ROOT_PATH environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export PSGA_ROOT_PATH="
    line: "export PSGA_ROOT_PATH={{ psga_root_path }}"
  register: psga_root_path_register

- name: PSGA pipeline - set PSGA_OUTPUT_PATH environment variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^export PSGA_OUTPUT_PATH="
    line: "export PSGA_OUTPUT_PATH={{ psga_output_path }}"
  register: psga_output_path_register

- name: PSGA pipeline - set environment extra variables
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "^{{ item.key }}="
    line: "export {{ item.key }}={{ item.value}}"
  with_items: "{{ environment_vars }}"

- name: PSGA pipeline - source changed bashrc file
  shell: source ~/.bashrc
  when: db_host_register.changed or db_name_register.changed or db_user_register.changed or db_password_register.changed or db_port_register.changed or psga_root_path_register.changed or psga_input_path_register.changed or psga_output_path_register.changed

- name: PSGA pipeline - stat start_pipeline.sh script
  stat:
    path: "{{ start_pipeline_script.path }}"
  register: spscript

- name: PSGA pipeline - run start_pipeline script cron
  cron:
    name: "run start_pipeline.sh"
    minute: "0"
    hour: "*/{{ cron.hourly }}"
    job: "source ${HOME}/.bashrc && {{ spscript.stat.path }} > ${HOME}/crontab.log 2> ${HOME}/crontab.err"
  when: spscript.stat.exists == True and spscript.stat.readable == True and spscript.stat.executable == True
