---
pipeline:
  name: Synthetic
  docker_image: "synthetic-pipeline"

pipeline_version:
  docker_tag: dev_latest

input_fields: []
#input_row_validation_rules:
#- {}
#
#input_set_validation_rules:
#- {}

output_fields:
  - field_name: STATUS
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: QC_STATUS
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: REGION_OF_DIFFERENCE
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: LINEAGE
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null
#output_row_validation_rules:
#- {}
#
#output_set_validation_rules:
#- {}
