---
pipeline:
  name: SARS CoV 2
  docker_image: "sars-cov-2-pipeline"
  protocols:
    # unknown primer

    - name: illumina-sars-cov-2-unknown
      kit:
        name: Unknown
        slug: unknown
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-unknown
      kit:
        name: Unknown
        slug: unknown
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC_V1
    - name: illumina-sars-cov-2-articv1
      kit:
        name: ARTIC V1
        slug: ARTIC_V1
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv1
      kit:
        name: ARTIC V1
        slug: ARTIC_V1
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC_V2
    - name: illumina-sars-cov-2-articv2
      kit:
        name: ARTIC V2
        slug: ARTIC_V2
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv2
      kit:
        name: ARTIC V2
        slug: ARTIC_V2
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V3
    - name: illumina-sars-cov-2-articv3
      kit:
        name: ARTIC V3
        slug: ARTIC_V3
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv3
      kit:
        name: ARTIC V3
        slug: ARTIC_V3
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V4
    - name: illumina-sars-cov-2-articv4
      kit:
        name: ARTIC V4
        slug: ARTIC_V4
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv4
      kit:
        name: ARTIC V4
        slug: ARTIC_V4
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V4.1
    - name: illumina-sars-cov-2-articv4-1
      kit:
        name: ARTIC V4.1
        slug: ARTIC_V4-1
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv4-1
      kit:
        name: ARTIC V4.1
        slug: ARTIC_V4-1
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V5.0.0-400
    - name: illumina-sars-cov-2-articv5-0-0-400
      kit:
        name: ARTIC V5.0.0-400
        slug: ARTIC_v5-0-0-400
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv5-0-0-400
      kit:
        name: ARTIC V5.0.0-400
        slug: ARTIC_v5-0-0-400
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V5.1.0-400
    - name: illumina-sars-cov-2-articv5-1-0-400
      kit:
        name: ARTIC V5.1.0-400
        slug: ARTIC_v5-1-0-400
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv5-1-0-400
      kit:
        name: ARTIC V5.1.0-400
        slug: ARTIC_v5-1-0-400
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V5.2.0-1200
    - name: illumina-sars-cov-2-articv5-2-0-1200
      kit:
        name: ARTIC V5.2.0-1200
        slug: ARTIC_v5-2-0-1200
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv5-2-0-1200
      kit:
        name: ARTIC V5.2.0-1200
        slug: ARTIC_v5-2-0-1200
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V5.2.0-400
    - name: illumina-sars-cov-2-articv5-2-0-400
      kit:
        name: ARTIC V5.2.0-400
        slug: ARTIC_v5-2-0-400
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv5-2-0-400
      kit:
        name: ARTIC V5.2.0-400
        slug: ARTIC_v5-2-0-400
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # ARTIC V5.3.2-400
    - name: illumina-sars-cov-2-articv5-3-2-400
      kit:
        name: ARTIC V5.3.2-400
        slug: ARTIC_v5-3-2-400
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    - name: ont-sars-cov-2-articv5-3-2-400
      kit:
        name: ARTIC V5.3.2-400
        slug: ARTIC_v5-3-2-400
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # Midnight-IDT_V1
    - name: ont-sars-cov-2-midnight-idt-v1
      kit:
        name: Midnight IDT V1
        slug: Midnight-IDT_v1
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # Midnight-ONT_V1

    - name: ont-sars-cov-2-midnight-ont-v1
      kit:
        name: Midnight ONT V1
        slug: Midnight-ONT_V1
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # Midnight ONT V2

    - name: ont-sars-cov-2-midnight-ont-v2
      kit:
        name: Midnight ONT V2
        slug: Midnight-ONT_V2
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # Midnight ONT V3

    - name: ont-sars-cov-2-midnight-ont-v3
      kit:
        name: Midnight ONT V3
        slug: Midnight-ONT_V3
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # FASTA
    - name: sars-cov-2-fasta
      kit:
        name: None
        slug: none
      sequencer_technology:
        name: Unknown
        slug: unknown
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # NEB-VarSkip_v1a

    - name: ont-sars-cov-2-neb-varskip-v1a
      kit:
        name: NEB VarSkip v1a
        slug: neb-varskip-v1a
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # NEB VarSkip v1a-long

    - name: ont-sars-cov-2-neb-varskip-v1a-long
      kit:
        name: NEB VarSkip v1a-long
        slug: neb-varskip-v1a-long
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # NEB VarSkip v2

    - name: ont-sars-cov-2-neb-varskip-v2
      kit:
        name: NEB VarSkip v2
        slug: neb-varskip-v2
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

    # NEB VarSkip v2b
    - name: ont-sars-cov-2-neb-varskip-v2b
      kit:
        name: NEB VarSkip v2b
        slug: neb-varskip-v2b
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: SARS CoV 2
        slug: sars-cov-2

pipeline_version:
  docker_tag: dev_latest

input_fields: []

# input_row_validation_rules: []
# input_set_validation_rules: []

output_fields:
  - field_name: STATUS
    field_type: string
    ui:
      name: "Status"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: CONTAMINATED_READS
    field_type: number
    ui:
      name: "Contaminated Reads"
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_INPUT
    field_type: string
    ui:
      name: "Primer Input"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PRIMER_DETECTED
    field_type: string
    ui:
      name: "Primer Detected"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PRIMER_NUMREADS
    field_type: number
    ui:
      name: "Primer Number Reads"
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_UNIQUE_NUMREADS
    field_type: number
    ui:
      name: "Primer Unique Number Reads"
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_AMBIGUOUS_NUMREADS
    field_type: number
    ui:
      name: "Primer Ambiguous Number Reads"
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_COVERAGE
    field_type: string
    ui:
      name: "Primer Coverage"
      format: "style: percent"
    required: true

  - field_name: NCOV_PCT_N_BASES
    field_type: number
    ui:
      name: "NCOV N bases"
      format: "style: percent"
      divisor: 100
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_PCT_COVERED_BASES
    field_type: number
    ui:
      name: "NCOV Covered Bases"
      format: "style: percent"
      divisor: 100
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_LONGEST_NO_N_RUN
    field_type: number
    ui:
      name: "NCOV Longest Number N Run"
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_NUM_ALIGNED_READS
    field_type: number
    ui:
      name: "NCOV Number Aligned Reads"
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_QC_PASS
    field_type: string
    ui:
      name: "NCOV QC Pass"
    required: true
    validation_rules:
      - rule_type: enum
        values:
          - "True"
          - "False"
      - rule_type: not_null

  - field_name: PANGOLIN_LINEAGE
    field_type: string
    ui:
      name: "Pangolin Lineage"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_CONFLICT
    field_type: string
    ui:
      name: "Pangolin Conflict"
    required: true

  - field_name: PANGOLIN_AMBIGUITY_SCORE
    field_type: string
    ui:
      name: "Pangolin Ambiguity Score"
    required: true

  - field_name: PANGOLIN_SCORPIO_CALL
    field_type: string
    ui:
      name: "Pangolin Scorpio Call"
    required: true

  - field_name: PANGOLIN_SCORPIO_SUPPORT
    field_type: string
    ui:
      name: "Pangolin Scorpia Support"
    required: true

  - field_name: PANGOLIN_SCORPIO_CONFLICT
    field_type: string
    ui:
      name: "Pangolin Scorpio Conflict"
    required: true

  - field_name: PANGOLIN_SCORPIO_NOTES
    field_type: string
    ui:
      name: "Pangolin Scorpia Notes"
    required: true

  - field_name: PANGOLIN_PANGO_DESIGNATION_VERSION
    field_type: string
    ui:
      name: "Pangolin Pango Designation Version"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_VERSION
    field_type: string
    ui:
      name: "Pangolin Version"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_SCORPIO_VERSION
    field_type: string
    ui:
      name: "Pangolin Scorpio Version"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_CONSTELLATION_VERSION
    field_type: string
    ui:
      name: "Pangolin Constellation Version"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_IS_DESIGNATED
    field_type: string
    ui:
      name: "Pangolin Is Designated"
    required: true
    validation_rules:
      - rule_type: enum
        values:
          - "True"
          - "False"

  - field_name: PANGOLIN_QC_STATUS
    field_type: string
    ui:
      name: "Pangolin QC Status"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_QC_NOTES
    field_type: string
    ui:
      name: "Pangolin QC Notes"
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_NOTE
    field_type: string
    ui:
      name: "Pangolin Note"
    required: true

# output_row_validation_rules: []
# output_set_validation_rules: []

settings:
  - field_name: sequencing_technology
    field_type: "string"
    # TODO: This setting should be `required: true`. It has been set to `false` for now
    #   to ensure that the existing protocols using this pipeline don't break while we
    #   implement the settings value definition for protocols in the backend.
    #   Once the protocols have all a value set for this field, we must make it required.    
    required: false
    validation_rules:
      - rule_type: enum
        values: ["illumina", "ont", "unknown"]
  - field_name: kit
    field_type: "string"
