---
pipeline:
  name: SARS CoV 2
  slug: sars-cov-2
  docker_image: "sars-cov-2-pipeline"

pipeline_version:
  docker_tag: dev_latest

input_fields:
  - field_name: seq_file
    field_type: file_group
    required: true
    read_only: true
    validation_rules:
      - rule_type: file_list
        file_type_combinations:
          - file_type: FASTQ
            content_type: fastq/raw
            reprocessing_content_type: fastq/cleaned-sequence-data
            max_number: 2
            groups: 2
            sequencing_technology: illumina
          - file_type: FASTQ_GZ
            content_type: fastq/raw
            reprocessing_content_type: fastq/cleaned-sequence-data
            max_number: 2
            groups: 2
            sequencing_technology: illumina
          - file_type: FASTQ
            content_type: fastq/raw
            reprocessing_content_type: fastq/cleaned-sequence-data
            max_number: 1
            groups: 1
            sequencing_technology: ont
          - file_type: FASTQ_GZ
            content_type: fastq/raw
            reprocessing_content_type: fastq/cleaned-sequence-data
            max_number: 1
            groups: 1
            sequencing_technology: ont
          - file_type: FASTA
            content_type: fasta/raw
            reprocessing_content_type: fasta/raw
            max_number: 1
            groups: 1
            sequencing_technology: unknown

#input_row_validation_rules: []
#input_set_validation_rules: []

output_fields:
  - field_name: STATUS
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: CONTAMINATED_READS
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_INPUT
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PRIMER_DETECTED
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PRIMER_NUMREADS
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_UNIQUE_NUMREADS
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: PRIMER_COVERAGE
    field_type: string
    required: true

  - field_name: NCOV_PCT_N_BASES
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_PCT_COVERED_BASES
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_LONGEST_NO_N_RUN
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_NUM_ALIGNED_READS
    field_type: number
    required: true
    validation_rules:
      - rule_type: integer
      - rule_type: not_null

  - field_name: NCOV_QC_PASS
    field_type: string
    required: true
    validation_rules:
      - rule_type: enum
        values:
          - "True"
          - "False"
      - rule_type: not_null

  - field_name: PANGOLIN_LINEAGE
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_CONFLICT
    field_type: string
    required: true

  - field_name: PANGOLIN_AMBIGUITY_SCORE
    field_type: string
    required: true

  - field_name: PANGOLIN_SCORPIO_CALL
    field_type: string
    required: true

  - field_name: PANGOLIN_SCORPIO_SUPPORT
    field_type: string
    required: true

  - field_name: PANGOLIN_SCORPIO_CONFLICT
    field_type: string
    required: true

  - field_name: PANGOLIN_SCORPIO_NOTES
    field_type: string
    required: true

  - field_name: PANGOLIN_PANGO_DESIGNATION_VERSION
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_VERSION
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_SCORPIO_VERSION
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_CONSTELLATION_VERSION
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_IS_DESIGNATED
    field_type: string
    required: true
    validation_rules:
      - rule_type: enum
        values:
          - "True"
          - "False"

  - field_name: PANGOLIN_QC_STATUS
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_QC_NOTES
    field_type: string
    required: true
    validation_rules:
      - rule_type: not_null

  - field_name: PANGOLIN_NOTE
    field_type: string
    required: true

# output_row_validation_rules: []
# output_set_validation_rules: []

output_files:
  - file_type: FASTQ
    content_type: fastq/cleaned-sequence-data
    max_number: 2
    groups: 2
    sequencing_technology: illumina
  - file_type: FASTQ
    content_type: fastq/cleaned-sequence-data
    max_number: 1
    groups: 1
    sequencing_technology: ont
  - file_type: CSV
    content_type: csv/cleaned-sequence-count
    max_number: 1
  - file_type: TXT
    content_type: txt/cleaned-sequence-count
    max_number: 1

settings:
  - field_name: sequencing_technology
    field_type: "string"
    required: true
    validation_rules:
      - rule_type: enum
        values: ["illumina", "ont", "unknown"]
  - field_name: kit
    field_type: "string"
    required: true
    validation_rules:
      - rule_type: enum
        values:
          - ARTIC_V1
          - ARTIC_V2
          - ARTIC_V3
          - ARTIC_V4
          - ARTIC_V4-1
          - ARTIC_v5-0-0-400
          - ARTIC_v5-1-0-400
          - ARTIC_v5-2-0-1200
          - ARTIC_v5-2-0-400
          - ARTIC_v5-3-2-400
          - Midnight-IDT_v1
          - Midnight-ONT_V1
          - Midnight-ONT_V2
          - Midnight-ONT_V3
          - neb-varskip-v1a
          - neb-varskip-v1a-long
          - neb-varskip-v2
          - neb-varskip-v2b
          - unknown
          - none
