---
pipeline:
  name: Staphylococcus aureus
  docker_image: "s-aureus-pipeline"
  protocols:
    # primer does not matter for pipeline

    - name: illumina-s-aureus-unknown
      kit:
        name: Unknown
        slug: unknown
      sequencer_technology:
        name: Illumina
        slug: illumina
      pathogen:
        name: Staphylococcus aureus
        slug: s-aureus

    - name: ont-s-aureus-unknown
      kit:
        name: Unknown
        slug: unknown
      sequencer_technology:
        name: ONT
        slug: ont
      pathogen:
        name: Staphylococcus aureus
        slug: s-aureus

pipeline_version:
  docker_tag: dev_latest

input_fields:
  - field_name: sample_id
    field_type: string
    required: true
    validation_rules:
      - rule_type: min_max
        min: 36
        max: 36
      - rule_type: regex
        expression: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

#input_row_validation_rules:
#- {}
#
#input_set_validation_rules:
#- {}

output_fields:
  - field_name: SAMPLE_ID
    field_type: string
    required: true
    validation_rules:
      - rule_type: min_max
        min: 36
        max: 36
      - rule_type: regex
        expression: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

  - field_name: STATUS
    field_type: string
    required: false

  - field_name: QC_STATUS
    field_type: string
    required: false

  - field_name: "mlst-version"
    field_type: string
    required: false

  - field_name: "mykrobe-version"
    field_type: string
    required: false

  - field_name: "Annotation-organism"
    field_type: string
    required: false

  - field_name: "Annotation-contigs"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Annotation-bases"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Annotation-CDS"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Annotation-gene"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Annotation-rRNA"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Annotation-tRNA"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Annotation-tmRNA"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Variant-COMPLEX"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Variant-DEL"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Variant-INS"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Variant-SNP"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "Marker lineage"
    field_type: string
    required: false

  - field_name: "Completeness"
    field_type: string
    required: false

  - field_name: "Contamination"
    field_type: string
    required: false

  - field_name: "Strain heterogeneity"
    field_type: string
    required: false

  - field_name: "VariantTotal"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "total_contig"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "total_contig_length"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "max_contig_length"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "mean_contig_length"
    field_type: string
    required: false

  - field_name: "median_contig_length"
    field_type: string
    required: false

  - field_name: "min_contig_length"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "n50_contig_length"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "l50_contig_count"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "num_contig_non_acgtn"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "contig_percent_a"
    field_type: string
    required: false

  - field_name: "contig_percent_c"
    field_type: string
    required: false

  - field_name: "contig_percent_g"
    field_type: string
    required: false

  - field_name: "contig_percent_t"
    field_type: string
    required: false

  - field_name: "contig_percent_n"
    field_type: string
    required: false

  - field_name: "contig_non_acgtn"
    field_type: string
    required: false

  - field_name: "contigs_greater_1m"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "contigs_greater_100k"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "contigs_greater_10k"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "contigs_greater_1k"
    field_type: number
    required: false
    validation_rules:
      - rule_type: integer

  - field_name: "percent_contigs_greater_1m"
    field_type: string
    required: false

  - field_name: "percent_contigs_greater_100k"
    field_type: string
    required: false

  - field_name: "percent_contigs_greater_10k"
    field_type: string
    required: false

  - field_name: "percent_contigs_greater_1k"
    field_type: string
    required: false

  - field_name: "Antimicrobial resistance genes"
    field_type: string
    required: false

  - field_name: "Annotation-repeat_region"
    field_type: string
    required: false
#output_row_validation_rules:
#- {}
#
#output_set_validation_rules:
#- {}
