---
- name: PSGA pipeline - yum update
  yum:
    name: '*'
    state: latest
  when: yum_update == true

- name: PSGA pipeline - add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: PSGA pipeline - install pre-requisite software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - wget
    - epel-release
    - python3-pip
    - awscli
    - samtools
    - java
    - java-11-openjdk-headless
    - python-docker
    - yum-utils
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - postgresql

- name: PSGA pipeline - pre-create docker config directory
  file:
    path: /etc/docker
    state: directory

- name: PSGA pipeline - set custom docker networking config
  template:
    src: docker_daemon.j2
    dest: /etc/docker/daemon.json

- name: PSGA pipeline - enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes
