apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: psga-minikube
  name: psga-minikube-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: pip-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
