apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-minikube-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: db-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: psql-minikube-host
  labels:
    app: psql
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: psql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-minikube
spec:
  selector:
    matchLabels:
      app: psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - image: 144563655722.dkr.ecr.eu-west-1.amazonaws.com/congenica/dev/covid-pipeline-db:1.0.0
        name: psql
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: psql
        volumeMounts:
        - name: psql-persistent-storage
          mountPath: /var/lib/psql
      volumes:
      - name: psql-persistent-storage
        persistentVolumeClaim:
          claimName: psql-minikube-pvc
