---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ukhsa-covid-minikube
  name: psga-minikube-admin
  labels:
    app: psga
    app.kubernetes.io/name: psga
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/part-of: covid
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["jobs", "jobs/status"]
  verbs: ["get","list","create","delete"]
- apiGroups: [""]
  resources: ["configmaps", "pods", "pods/status", "pods/exec"]
  verbs: ["get","list","create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get","list","create","delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ukhsa-covid-minikube
  name: psga-minikube-admin
  labels:
    app: psga
    app.kubernetes.io/name: psga
    app.kubernetes.io/component: pipe
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ukhsa-covid-minikube
  name: psga-minikube-admin
  labels:
    app: psga
    app.kubernetes.io/name: psga
    app.kubernetes.io/component: pipe
subjects:
- kind: ServiceAccount
  namespace: ukhsa-covid-minikube
  name: psga-minikube-admin
roleRef:
  kind: Role
  name: psga-minikube-admin
  apiGroup: rbac.authorization.k8s.io
