name: psga
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nextflow=22.04.5  # Need lower version because conda disabled by default in higher versions (maybe use newer version and enable conda)
  - make=4.3
  - gcc=12.1.0
  - python=3.9.14     # Required by bactopia (must be below v3.10)
  - bactopia=2.1.1    # Supposedly "Incompatible" with art below but mamba is happy
  - graphviz=6.0.2
  - fastq-scan=1.0.1
  - jq=1.5
  - fastq-dl=1.1.1
  - pigz=2.6
  - sra-tools=2.9.6
  - art=2016.06.05
  - awscli=1.25.92
  - pip:
    - PyYAML==6.0
