---
- hosts: all
  gather_facts: true
  become: false

  # Ensure that valid credentials can be provided when requested by the playbook.

  vars_files:
    - vars/env_vars.yml

  vars_prompt:
    - name: db_host
      prompt: 'Database hostname/ip '
      private: no
      default: "{{ lookup('env', 'DB_HOST') | default('localhost', True) }}"
    - name: db_name
      prompt: 'Database logical name '
      private: no
      default: "{{ lookup('env', 'DB_NAME') | default('bahrain_sars_cov_2', True) }}"
    - name: db_user
      prompt: 'Database username '
      private: no
      default: "{{ lookup('env', 'DB_USER') | default('postgres', True) }}"
    - name: db_port
      prompt: 'Database port '
      private: no
      default: "{{ lookup('env', 'DB_PORT') | default('5432', True) }}"
    - name: db_password
      prompt: 'Database password '
      private: yes
      confirm: yes
    - name: covid_pipeline_rootdir
      prompt: 'Root dir of the pipeline '
      private: no
      default: '${HOME}/ps-bahrain-covid'
    - name: covid_pipeline_fastq_path
      prompt: 'Path to FASTQ files for pipeline '
      private: no
      default: '${HOME}/Bahrain_COVID_s3_data_lite/sample_data'
    - name: covid_pipeline_workdir
      prompt: 'Work dir of the pipeline '
      private: no
      default: '${HOME}/covid-pipeline'
    - name: covid_pipeline_reports_path
      prompt: 'Report path for pipeline '
      private: no
      default: '${HOME}/reports'

  roles:
    - { role: install-os-packages, yum_update: false, become: true }
    - { role: install-nextflow }
    - { role: build-pangolin }
    - { role: build-ncov }
    - { role: build-covid-pipeline }
    - { role: build-nextstrain }
    - { role: build-auspice }
    - { role: run-sqitch }
    - { role: post-install-setup }
