---
- name: PSGA pipeline - create install dir for sqitch
  file:
    path: ~/sqitch
    state: directory

- name: ARS-CoV-2 pipeline - stat sqitch
  stat:
    path: ~/sqitch/sqitch
  register: sqitch

- name: PSGA pipeline - install nextflow
  shell: curl -L https://git.io/JJKCn -o sqitch && chmod +x sqitch
  args:
    chdir: ~/sqitch
  when: sqitch.stat.exists == False or sqitch.stat.executable == False
  register: sqitchInstalled

- name: PSGA pipeline - add sqitch to $PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:~/sqitch/'
  when: sqitchInstalled.changed

- name: PSGA pipeline - ensure "{{ ansible_user_id }}" is in group docker
  user:
   name: "{{ ansible_user_id }}"
   groups: docker
   append: yes
  become: yes

- name: reset ssh connection
  meta: reset_connection

- name: PSGA pipeline - create database
  shell: "PGPASSWORD={{ db_password }} psql --host={{ db_host }} --port={{ db_port }} --username={{ db_user }} -c 'create database {{ db_name }}'"
  ignore_errors: yes

- name: PSGA pipeline - do sqitch deploy
  community.general.docker_container:
    name: sqitch
    image: sqitch/sqitch
    command: "--db-host {{ db_host }} --db-port {{ db_port }} --db-user {{ db_user }} deploy db:pg:{{ db_name }}"
    working_dir: /sqitch
    volumes:
      - "{{ repo.path }}/sqitch:/sqitch"
    env:
      PGPASSWORD: "{{ db_password }}"
    detach: false
