---
- name: SARS-CoV-2 pipeline - create install dir for sqitch
  file:
    path: ~/sqitch
    state: directory

- name: ARS-CoV-2 pipeline - stat sqitch
  stat:
    path: ~/sqitch/sqitch
  register: sqitch

- name: SARS-CoV-2 pipeline - install nextflow
  shell: curl -L https://git.io/JJKCn -o sqitch && chmod +x sqitch
  args:
    chdir: ~/sqitch
  when: sqitch.stat.exists == False or sqitch.stat.executable == False
  register: sqitchInstalled

- name: SARS-CoV-2 pipeline - add sqitch to $PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:~/sqitch/'
  when: sqitchInstalled.changed

- name: SARS-CoV-2 pipeline - ensure "{{ ansible_user_id }}" is in group docker
  user:
   name: "{{ ansible_user_id }}"
   groups: docker
   append: yes
  become: yes

- name: reset ssh connection
  meta: reset_connection

- name: SARS-CoV-2 pipeline - do sqitch deploy
  shell: "sqitch --db-host {{ db_host }} --db-port {{ db_port }} --db-user {{ db_user }} deploy db:pg:{{ db_name }}"
  args:
    chdir: "{{ repo.path }}/sqitch"
  environment:
    PGPASSWORD: "{{ db_password }}"