---
- name: SARS-CoV-2 pipeline - clone the pangolin git repo
  git:
    repo: 'https://github.com/cov-lineages/pangolin.git'
    dest: ~/pangolin

# need to add some checks here that will look for an existing pangolin environment
- name: SARS-CoV-2 pipeline - create the pangolin conda environment
  shell: source ~/.bashrc && conda env create -f ~/pangolin/environment.yml

# add something to check if 'conda init' has been run already
- name: SARS-CoV-2 pipeline - conda init
  shell: source ~/.bashrc &&  conda init

- name: SARS-CoV-2 pipeline - activate the pangolin conda env
  shell: source ~/.bashrc && conda activate pangolin && cd ~/pangolin && python setup.py install

- name: SARS-CoV-2 pipeline - cov-lineages/pangoLEARN install in pangolin conda env
  shell: source ~/.bashrc && conda activate pangolin && cd ~/pangolin && pip install git+https://github.com/cov-lineages/pangoLEARN.git --upgrade

- name: SARS-CoV-2 pipeline - cov-lineages/lineages install in pangolin conda env
  shell: source ~/.bashrc && conda activate pangolin && cd ~/pangolin && pip install git+https://github.com/cov-lineages/lineages.git --upgrade
