name: Build docker image
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      dockerfile_path:
        type: string
        required: true
      pathogen:
        type: string
        required: false
        default: ~
      ecr_path:
        type: string
        required: true
      push:
        type: boolean
        default: false
        required: false
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - run: |
          set -e
          BRANCH_NAME=${GITHUB_REF/refs\/heads\//}
          IMAGE_NAME="${{ inputs.name }}:${{ github.sha }}"
          ECR_IMAGE_NAME="${{ inputs.ecr_path }}/${IMAGE_NAME}"
          ECR_BRANCH_LATEST_NAME="${{ inputs.ecr_path }}/${IMAGE_NAME}:${BRANCH_NAME}_latest"
          PATHOGEN_ARG=""
          if [[ ! -z "${{ inputs.pathogen }}" ]]; then
            PATHOGEN_ARG="--build-arg pathogen=${{ inputs.pathogen }}"
          fi
          docker build ${PATHOGEN_ARG} -t $ECR_IMAGE_NAME -t $ECR_BRANCH_LATEST_NAME -f docker/${{ inputs.dockerfile_path }} .
