name: Build docker image
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      dockerfile:
        type: string
        required: true
      pathogen:
        type: string
        required: false
        default: ~
      ecr_path:
        type: string
        required: false
        default: dev
      push:
        type: boolean
        default: false
        required: false
      version:
        type: string
        required: false
        default: ~
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - run: |
          set -e
          BRANCH_NAME=${GITHUB_REF/refs\/heads\//}
          VERSION=${{ github.sha }}
          if [[ ! -z "${{ inputs.version }}" ]]; then
            VERSION=${{ inputs.version }}
          fi
          if [[ "${{ inputs.ecr_path }}" == "prod" ]]; then
            ECR_PATH=${{ secrets.ECR_PATH_PROD }}
          else
            ECR_PATH=${{ secrets.ECR_PATH_DEV }}
          fi
          IMAGE_NAME="${{ inputs.name }}:${VERSION}"
          ECR_IMAGE_NAME="${ECR_PATH}/${IMAGE_NAME}"
          ECR_BRANCH_LATEST_NAME="${ECR_PATH}/${{ inputs.name }}:${BRANCH_NAME}_latest"
          PATHOGEN_ARG=""
          if [[ ! -z "${{ inputs.pathogen }}" ]]; then
            PATHOGEN_ARG="--build-arg pathogen=${{ inputs.pathogen }}"
          fi
          docker build ${PATHOGEN_ARG} -t $ECR_IMAGE_NAME -t $ECR_BRANCH_LATEST_NAME -f docker/${{ inputs.dockerfile }} .
