name: Run integration tests
on:
  workflow_call:
    secrets:
      CICD_OIDC_ROLE:
        required: true
      GH_PSGA_SYSTEM_PAT:
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  vars:
    runs-on: ubuntu-22.04
    environment: nonprod # TBD: this is a WIP workflow
    outputs:
      CICD_OIDC_ROLE: ${{ vars.CICD_OIDC_ROLE }}
      GH_RUNNER_SUBNET_ID: ${{ vars.GH_RUNNER_SUBNET_ID }}
      GH_RUNNER_SECURITY_GROUP_ID: ${{ vars.GH_RUNNER_SECURITY_GROUP_ID }}
      GH_RUNNER_IAM_ROLE_NAME: ${{ vars.GH_RUNNER_IAM_ROLE_NAME }}
    steps:
      - run: echo "Exposing env vars"

  start-runner:
    uses: Congenica/psga-reusable-workflows/.github/workflows/ec2-runner-start.yaml@main
    needs: vars
    secrets:
      role-to-assume: ${{ needs.vars.outputs.CICD_OIDC_ROLE }}
      github-token: ${{ secrets.GH_PSGA_SYSTEM_PAT }}
    with:
      aws-region: ${{ vars.AWS_REGION }}
      ec2-instance-type: m5.2xlarge
      subnet-id: ${{  needs.vars.outputs.GH_RUNNER_SUBNET_ID }}
      security-group-id: ${{  needs.vars.outputs.GH_RUNNER_SECURITY_GROUP_ID }}
      iam-role-name: ${{  needs.vars.outputs.GH_RUNNER_IAM_ROLE_NAME }}
      env_type: ${{ inputs.actions_env }}

  integration_tests:
    name: Integration Tests
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }}
    environment: ${{ inputs.actions_env }}
    steps:
      #   - name: Check out repo
      #     uses: actions/checkout@v4

      #   - name: Configure AWS Credentials
      #     id: creds
      #     uses: aws-actions/configure-aws-credentials@v4
      #     with:
      #       aws-region: eu-west-2
      #       role-to-assume: ${{ secrets.CICD_OIDC_ROLE }}
      #       role-session-name: cicd-role-session
      #       mask-aws-account-id: false

      #   - name: Login to dev Amazon ECR
      #     uses: aws-actions/amazon-ecr-login@v2

      - name: Run tests
        run: |
          echo "run 3x integration tests here, one for each image"

  stop-runner:
    if: ${{ always() }} # required to stop the runner even if previous jobs failed or are cancelled
    needs:
      - start-runner # required to get output from the start-runner job
      - integration_tests # required to wait when the main job is done
    uses: Congenica/psga-reusable-workflows/.github/workflows/ec2-runner-stop.yaml@main
    secrets:
      role-to-assume: ${{ needs.vars.outputs.CICD_OIDC_ROLE }}
      github-token: ${{ secrets.GH_PSGA_SYSTEM_PAT }}
    with:
      aws-region: ${{ vars.AWS_REGION }}
      label: ${{ needs.start-runner.outputs.label }}
      ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
