name: Build, test and push
on:
  push:
    branches-ignore:
      - "release/**"
jobs:
  synthetic-pipeline:
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: synthetic-pipeline
      dockerfile: Dockefile.psga-pipeline
      pathogen: synthetic
  pangolin:
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: pangolin
      dockerfile: Dockerfile.pangolin
  check_and_test:
    name: Install dependencies and run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Pre-commit checks
        run: |
          pip install pre-commit==2.17.0
          pre-commit run --all-files
      - name: Install dependencies and run tests
        run: |
          poetry install
          poetry run pytest tests/
