name: Build, test and push
on:
  push:
    branches-ignore:
      - "release/**"
jobs:
  build_image:
    name: Build and push image
    needs:
      - check_and_test
    strategy:
      matrix:
        image:
          - name: synthetic-pipeline
            dockerfile: Dockerfile.psga-pipeline
            pathogen: synthetic
          - name: sars-cov-2-pipeline
            dockerfile: Dockerfile.psga-pipeline
            pathogen: sars_cov_2
          - name: fastqc
            pathogen: sars_cov_2
          - name: read-it-and-keep
            pathogen: sars_cov_2
          - name: primer-autodetection
            pathogen: sars_cov_2
          - name: pangolin
            pathogen: sars_cov_2
          - name: ncov2019-artic-nf-nanopore
            pathogen: sars_cov_2
          - name: ncov2019-artic-nf-illumina
            pathogen: sars_cov_2
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: ${{ matrix.image.name }}
      dockerfile: ${{ matrix.image.dockerfile }}
      pathogen: ${{ matrix.image.pathogen }}
  publish_configs:
    name: Publish configs
    needs: build_image
    uses: ./.github/workflows/publish_configs.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_PATH: ${{ secrets.S3_BUCKET_PATH_DEV }}
    with:
      publish_sha: true
  check_and_test:
    name: Install dependencies and run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Pre-commit checks
        run: |
          pip install pre-commit==2.17.0
          pre-commit run --all-files
      - name: Install dependencies and run tests
        run: |
          poetry install
          poetry run pytest tests/
