name: Build, test and push
on:
  push:
    branches-ignore:
      - "release/**"
jobs:
  synthetic-pipeline:
    needs: check_and_test
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: synthetic-pipeline
      dockerfile: Dockerfile.psga-pipeline
      pathogen: synthetic
  sars-cov-2-pipeline:
    needs: check_and_test
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: sars-cov-2-pipeline
      dockerfile: Dockerfile.psga-pipeline
      pathogen: sars-cov-2
  pangolin:
    needs: check_and_test
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: pangolin
      dockerfile: Dockerfile.pangolin
  ncov2019-artic-nf-nanopore:
    needs: check_and_test
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: ncov2019-artic-nf-nanopore
      dockerfile: Dockerfile.ncov2019-artic-nf-nanopore
  ncov2019-artic-nf-illumina:
    needs: check_and_test
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      name: ncov2019-artic-nf-illumina
      dockerfile: Dockerfile.ncov2019-artic-nf-illumina
  check_and_test:
    name: Install dependencies and run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Pre-commit checks
        run: |
          pip install pre-commit==2.17.0
          pre-commit run --all-files
      - name: Install dependencies and run tests
        run: |
          poetry install
          poetry run pytest tests/
