name: Build, test and push
on:
  push:
    branches-ignore:
      - "release/**"
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  synthetic-pipeline:
    uses: ./.github/workflows/build_image.yml
    secrets: inherit
    with:
      name: synthetic-pipeline
      dockerfile_path: docker/Dockefile.psga-pipeline
      pathogen: synthetic
      ecr_path: ${{ secrets.ECR_PATH_DEV }}
  pangolin:
    uses: ./.github/workflows/build_image.yml
    secrets: inherit
    with:
      name: pangolin
      dockerfile_path: docker/Dockerfile.pangolin
      ecr_path: ${{ secrets.ECR_PATH_DEV }}

  check_and_test:
    name: Install dependencies and run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Pre-commit checks
        run: |
          pip install pre-commit==2.17.0
          pre-commit run --all-files
      - name: Install dependencies and run tests
        run: |
          poetry install
          poetry run pytest tests/
