name: Publish config files
on:
  workflow_call:
    inputs:
      env_type:
        type: string
        default: nonprod
        required: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  upload:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env_type }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.CICD_OIDC_ROLE }}
          role-session-name: cicd-role-session
          mask-aws-account-id: false

      - name: Publish configs to artefacts S3 bucket
        run: |
          curl -Ls https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && \
            chmod +x /usr/local/bin/yq
          if [[ "${GITHUB_REF/refs\/heads\/}" == *"release/"* ]]; then
            VERSIONS="${GITHUB_REF/refs\/heads\/release\//}"
          else
            VERSIONS="${{ github.sha }} ${GITHUB_REF/refs\/heads\//}_latest"
          fi
          for version in $VERSIONS; do
            for config in $(ls app/config); do
              S3_PATH="${{ vars.ARTIFACTS_BUCKET_PATH }}/${version}/${config}"
              yq e -i ".pipeline_version.docker_tag = \"${version}\"" app/config/${config}
              echo "Publishing version ${version} for config ${config} to ${S3_PATH}"
              aws s3 cp app/config/${config} $S3_PATH
            done
          done
