name: Release branch
on:
  push:
    branches:
      - release/*

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build_release_image:
    runs-on: ubuntu-22.04
    environment: saas001
    name: Build and push the release image
    strategy:
      matrix:
        image:
          - sars-cov-2-pipeline
          - ncov2019-artic-nf-nanopore
          - ncov2019-artic-nf-illumina
          - pangolin
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up env
        run: |
          RELEASE_VERSION=${GITHUB_REF/refs\/heads\/release\//}
          echo "Release version: $RELEASE_VERSION, Github ref: ${GITHUB_REF}"
          ECR_PATH_RELENG=${{ vars.ECR_PATH_RELENG }}
          ECR_PATH_DEV=${{ vars.ECR_PATH_DEV }}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "DEV_IMAGE_NAME=$ECR_PATH_DEV/${{ matrix.image }}:${{ github.sha }}" >> $GITHUB_ENV
          echo "DEV_RELEASE_NAME=$ECR_PATH_DEV/${{ matrix.image }}:$RELEASE_VERSION" >> $GITHUB_ENV
          echo "PROD_RELEASE_NAME=$ECR_PATH_RELENG/${{ matrix.image }}:$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Configure dev AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ vars.CICD_OIDC_ROLE_DEV }}
          role-session-name: cicd-dev-role-session
          mask-aws-account-id: false

      - name: Login to dev Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull the docker image from dev, build the release image and push to dev
        run: |
          docker pull $DEV_IMAGE_NAME
          cat << EOF > full-version.properties
          github.base_ref = "${{ github.base_ref }}"
          github.ref = "${{ github.ref }}"
          github.ref_name = "${{ github.ref_name }}"
          github.repositoryUrl = "${{ github.repositoryUrl }}"
          github.run_id = "${{ github.run_id }}"
          github.run_number = "${{ github.run_number }}"
          github.run_attempt = "${{ github.run_attempt }}"
          github.sha = "${{ github.sha }}"
          EOF
          echo "$RELEASE_VERSION" > version.properties
          docker build --build-arg BASE_IMAGE=$DEV_IMAGE_NAME \
            -t $DEV_RELEASE_NAME \
            -t $PROD_RELEASE_NAME \
            -f docker/Dockerfile-release .
          docker push $DEV_RELEASE_NAME

      - name: Configure releng AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.CICD_OIDC_ROLE }}
          role-session-name: cicd-releng-role-session
          mask-aws-account-id: false

      - name: Login to prod Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the release image to prod
        run: docker push $PROD_RELEASE_NAME

  publish_configs:
    name: Publish configs
    needs:
      - build_release_image
    uses: ./.github/workflows/publish_configs.yaml
    with:
      env_type: saas001
