name: Release branch
on:
  push:
    branches:
      - release/*

jobs:
  publish_configs:
    name: Publish configs
    needs: build_release_image
    uses: ./.github/workflows/publish_configs.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_PATH: ${{ secrets.S3_BUCKET_PATH_PROD }}
    with:
      actions_env: prod
      release_enabled: true
  build_release_image:
    name: Build and push the release image
    runs-on: ubuntu-22.04
    environment: prod
    strategy:
      matrix:
        image:
          - s-aureus-pipeline
          - synthetic-pipeline
          - sars-cov-2-pipeline
          - ncov2019-artic-nf-nanopore
          - ncov2019-artic-nf-illumina
          - pangolin
          - read-it-and-keep
          - primer-autodetection
          - fastqc
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up env
        run: |
          RELEASE_VERSION=${GITHUB_REF/refs\/heads\/release\//}
          echo "Release version: $RELEASE_VERSION, Github ref: ${GITHUB_REF}"
          ECR_PATH_PROD=${{ secrets.ECR_PATH_PROD }}
          ECR_PATH_DEV=${{ secrets.ECR_PATH_DEV }}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "DEV_IMAGE_NAME=$ECR_PATH_DEV/${{ matrix.image }}:${{ github.sha }}" >> $GITHUB_ENV
          echo "DEV_RELEASE_NAME=$ECR_PATH_DEV/${{ matrix.image }}:$RELEASE_VERSION" >> $GITHUB_ENV
          echo "PROD_RELEASE_NAME=$ECR_PATH_PROD/${{ matrix.image }}:$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Configure AWS Credentials for dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: eu-west-2

      - name: Login to dev Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull the docker image from dev, build the release image and push to dev
        run: |
          docker pull $DEV_IMAGE_NAME
          cat << EOF > full-version.properties
          github.base_ref = "${{ github.base_ref }}"
          github.ref = "${{ github.ref }}"
          github.ref_name = "${{ github.ref_name }}"
          github.repositoryUrl = "${{ github.repositoryUrl }}"
          github.run_id = "${{ github.run_id }}"
          github.run_number = "${{ github.run_number }}"
          github.run_attempt = "${{ github.run_attempt }}"
          github.sha = "${{ github.sha }}"
          EOF
          echo "$RELEASE_VERSION" > version.properties
          docker build --build-arg BASE_IMAGE=$DEV_IMAGE_NAME \
            -t $DEV_RELEASE_NAME \
            -t $PROD_RELEASE_NAME \
            -f docker/Dockerfile-release .
          docker push $DEV_RELEASE_NAME

      - name: Configure prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to prod Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push the release image to prod
        run: docker push $PROD_RELEASE_NAME

  test_traceability:
    uses: ./.github/workflows/test_traceability.yml
    secrets: inherit
    with:
      docker_tag: dev_latest
      trace_to_jira: true
