name: Test traceability
on:
  workflow_call:
    inputs:
      docker_tag:
        description: "The Docker tag of the rt-test-traceability image to use"
        required: true
        type: string
      trace_to_jira:
        description: "Bool to control if tests should be traced back to Jira or not"
        required: true
        type: boolean

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  vars:
    runs-on: ubuntu-22.04
    environment: nonprod
    outputs:
      CICD_OIDC_ROLE: ${{ vars.CICD_OIDC_ROLE }}
      GH_RUNNER_SUBNET_ID: ${{ vars.GH_RUNNER_SUBNET_ID }}
      GH_RUNNER_SECURITY_GROUP_ID: ${{ vars.GH_RUNNER_SECURITY_GROUP_ID }}
      GH_RUNNER_IAM_ROLE_NAME: ${{ vars.GH_RUNNER_IAM_ROLE_NAME }}
    steps:
      - run: echo "Exposing env vars"

  start-runner:
    uses: Congenica/psga-reusable-workflows/.github/workflows/ec2-runner-start.yaml@main
    needs: vars
    secrets:
      role-to-assume: ${{ needs.vars.outputs.CICD_OIDC_ROLE }}
      github-token: ${{ secrets.GH_PSGA_SYSTEM_PAT }}
    with:
      aws-region: ${{ vars.AWS_REGION }}
      ec2-instance-type: ${{ vars.AWS_INSTANCE_TYPE }}
      subnet-id: ${{  needs.vars.outputs.GH_RUNNER_SUBNET_ID }}
      security-group-id: ${{  needs.vars.outputs.GH_RUNNER_SECURITY_GROUP_ID }}
      iam-role-name: ${{  needs.vars.outputs.GH_RUNNER_IAM_ROLE_NAME }}
      env_type: nonprod

  test-traceability-job:
    name: Run test-traceability
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }}
    env:
      CONGENICA_AWS_ACCOUNT_DEV: 144563655722.dkr.ecr.eu-west-1.amazonaws.com
      REPO_NAME: psga-pipeline-sars-cov-2

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ needs.vars.outputs.CICD_OIDC_ROLE }}
          role-session-name: cicd-role-session
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull test-traceability image from the Congenica dev ECR
        id: pull-test-traceability-image
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin "${{ env.CONGENICA_AWS_ACCOUNT_DEV }}"
          FULL_IMAGE_PATH=${{ env.CONGENICA_AWS_ACCOUNT_DEV }}/congenica/dev/rt-test-traceability:${{ inputs.docker_tag }}
          echo "TEST_TRACEABILITY_IMAGE=$FULL_IMAGE_PATH" >> $GITHUB_OUTPUT
          docker pull $FULL_IMAGE_PATH

      # Passes the most recent set of Allure Results from the current Git hash to the test traceability code. There
      # could be a race condition where two builds produce a set of Allure Results from the same Git hash at roughly the
      # same time, leading to the wrong set of Allure Results being used. However, the chances of this are minimal as
      # two builds executing against a single branch on the same Git hash is highly unlikely.
      - name: Run test traceability
        run: |
          BUCKET_URL_ROOT=s3://congenica-test-evidence/${{ env.REPO_NAME }}/unit
          BUCKET_URL_PARTIAL=$BUCKET_URL_ROOT/${{ github.sha }}
          ALLURE_ARTIFACT_NAME=$(aws s3 ls $BUCKET_URL_PARTIAL | awk '{print $4}' | tail -n1)
          BUCKET_URL_FULL=$BUCKET_URL_ROOT/$ALLURE_ARTIFACT_NAME
          docker run --env AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
                     --env AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                     --env TT_ALLURE_RESULTS_S3_URL="$BUCKET_URL_FULL" \
                     --env TT_JIRA_COMPONENT="Pipelines" \
                     --env TT_JIRA_PROJECT_KEY="PSG" \
                     --env TT_JIRA_TEST_TYPE="unit" \
                     --env TT_JIRA_TOKEN=${{ secrets.JIRA_TOKEN }} \
                     --env TT_REPO_NAME="${{ env.REPO_NAME }}" \
                     --env TT_SHOULD_TRACE_RESULTS_TO_JIRA=${{ inputs.trace_to_jira }} \
                     --rm \
                     ${{ steps.pull-test-traceability-image.outputs.TEST_TRACEABILITY_IMAGE }} \
                     /bin/bash -c "poetry run pytest -k TestTraceTests"

  stop-runner:
    if: ${{ always() }} # required to stop the runner even if previous jobs failed or are cancelled
    needs:
      - start-runner # required to get output from the start-runner job
      - test-traceability-job # required to wait when the main job is done
      - vars
    uses: Congenica/psga-reusable-workflows/.github/workflows/ec2-runner-stop.yaml@main
    secrets:
      role-to-assume: ${{ needs.vars.outputs.CICD_OIDC_ROLE }}
      github-token: ${{ secrets.GH_PSGA_SYSTEM_PAT }}
    with:
      aws-region: ${{ vars.AWS_REGION }}
      label: ${{ needs.start-runner.outputs.label }}
      ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
