---
- name: PSGA pipeline - init submodules
  command: git submodule init
  args:
    chdir: "{{ git_submod.path }}"

- name: PSGA pipeline - update submodules
  command: git submodule update --remote --merge
  args:
    chdir: "{{ git_submod.path }}"

- name: PSGA pipeline - ensure "{{ ansible_user_id }}" is in group docker
  user:
   name: "{{ ansible_user_id }}"
   groups: docker
   append: yes
  become: yes

- name: reset ssh connection
  meta: reset_connection

- name: PSGA pipeline - build ncov2019-artic-nf-illumina image
  community.general.docker_image:
    name: ncov2019-artic-nf-illumina
    build:
      path: "{{ docker_build.path }}"
      pull: no
      dockerfile: Dockerfile.ncov2019-artic-nf-illumina
    source: build
    state: present
    tag: 1.0.0
  become: yes

- name: PSGA pipeline - build ncov2019-artic-nf-nanopore image
  community.general.docker_image:
    name: ncov2019-artic-nf-nanopore
    build:
      path: "{{ docker_build.path }}"
      pull: no
      dockerfile: Dockerfile.ncov2019-artic-nf-nanopore
    source: build
    state: present
    tag: 1.0.0
  become: yes
