---
- name: SARS-CoV-2 pipeline - init submodules
  command: git submodule init
  args:
    chdir: "{{ git_submod.path }}"

- name: SARS-CoV-2 pipeline - update submodules
  command: git submodule update --remote --merge
  args:
    chdir: "{{ git_submod.path }}"

- name: SARS-CoV-2 pipeline - ensure "{{ ansible_user_id }}" is in group docker
  user:
   name: "{{ ansible_user_id }}"
   groups: docker
   append: yes
  become: yes

- name: reset ssh connection
  meta: reset_connection

- name: SARS-CoV-2 pipeline - build ncov2019_artic_nf_illumina image
  community.general.docker_image:
    name: ncov2019_artic_nf_illumina
    build:
      path: "{{ docker_build.path }}"
      pull: no
      dockerfile: Dockerfile.ncov2019-artic-nf-illumina
    source: build
    state: present
    tag: 1.0.0
  become: yes

- name: SARS-CoV-2 pipeline - build ncov2019_artic_nf_nanopore image
  community.general.docker_image:
    name: ncov2019_artic_nf_nanopore
    build:
      path: "{{ docker_build.path }}"
      pull: no
      dockerfile: Dockerfile.ncov2019-artic-nf-nanopore
    source: build
    state: present
    tag: 1.0.0
  become: yes
